apiVersion: v1
kind: Secret
metadata:
  name: "storageos-api"
  namespace: "storageos-operator"
  labels:
    app: "storageos"
type: "kubernetes.io/storageos"
data:
  # echo -n '<secret>' | base64
  apiUsername: YWRtaW4=
  apiPassword: MTIzNDU2Nzg=
  # CSI Credentials
  csiProvisionUsername: YWRtaW4=
  csiProvisionPassword: MTIzNDU2Nzg=
  csiControllerPublishUsername: YWRtaW4=
  csiControllerPublishPassword: MTIzNDU2Nzg=
  csiNodePublishUsername: YWRtaW4=
  csiNodePublishPassword: MTIzNDU2Nzg=
  csiControllerExpandUsername: YWRtaW4=
  csiControllerExpandPassword: MTIzNDU2Nzg=